baseURL: "https://zomzog.fr/"
languageCode: "fr-fr"
title: "Zomzog's blog"
theme: "hugo-theme-bootstrap"
# number of posts to show on home/category/tag pages (Default: 10)
paginate: 5
# optionally override the site's footer with  copyright text
copyright: "All code and content for this blog is available as [open source on GitHub](https://github.com/zomzog/zomzog.fr)."
#googleAnalytics: "UA-123-45"
disqusShortname: "zomzog"

permalinks:
  post: "/:year/:month/:title/"
  page: "/:slug/"


author:
  name: "Thibault Duperron"
  avatar: https://s.gravatar.com/avatar/0a71ca60d71fa5dcefb541ad69d02a41?s=200
  bio: "Hi, I'm Thibault Duperron a simple developer, evangelist of the Pony Driven Development."
social:
  github: "Zomzog"
  linkedin: "thibault-duperron-76446435"
  email: "zomzog@zomzog.fr"
  twitter: Zomzog

# Theme variables
#
params:
  # Description/subtitle for homepage (can be Markdown)
  description: ""
  logo: https://s.gravatar.com/avatar/0a71ca60d71fa5dcefb541ad69d02a41?s=200
  
  email: "zomzog@gmail.com"

  # Format dates with Go's time formatting
  date_format: "Mon 02 Jan 2006"

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  disable_sri: true
  
  # Add non min js
  cleanjs: true

  sidebar:
    # Optional about block for sidebar (can be Markdown)

    # How many posts to show on the sidebar (Default: 5)
    #num_recent_posts: 2

  #Theme
  color: dark

# Default content language for Hugo 0.17's multilingual support (default is "en")
# See: https://github.com/spf13/hugo/blob/master/docs/content/content/multilingual.md
#DefaultContentLanguage: "en"

# Languages to render
#[languages.en]
#[languages.bg]

# vim: ts=2 sw=2 et
